# Name of our action
name: 'Test'
# The event that will trigger the action
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - development
      - testing

# What the action will do
jobs:
  test:
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn

      - name: run vitest
        run: yarn tnw

      - name: run test-lint
        run: yarn lint
        
      - name: run test-typecheck
        run: yarn typecheck
